### ISSUE TITLE
ArchUnit Tests

### ISSUE THREAD

**Issue by garogarabed12** [n2o/url-shortener#40]
Hello!

I noticed there aren't any architecture tests, so I thought about writing a few with ArchUnit and adding them.

Looking at the project structure, I can tell the layered architecture was used (please correct me if I'm wrong), so in addition to testing that, I would also like to add some tests to check the proper naming, annotation and location of the classes.

Looking forward to your feedback!
Garo

**Comment by n2o** [comment]
Hi Garo,
feel free to play around with this repository and send a Pull Request, if you like :-) This project is, as you know, just a small project built with the students of our course, and apparently there was no time for this. Also, it is just a small project, which is why it might not be that essential to have ArchUnit-Tests. But feel free to submit a PR 👍
Greetings

**Comment by garogarabed12** [comment]
Hi Christian, and thanks for your response.

Well, since it's part of the course and was just for learning purposes, I guess I'd just leave it as it is :)

Thanks again, and best regards!
Garo

**Comment by n2o** [comment]
Hey,
actually this is not only part of the course, it is still being used in production at the Computer Science Institute at the HHU. So there is still relevance for this project ;-)

**Comment by garogarabed12** [comment]
Hi Christian,

Alright, I'll just go ahead and submit a PR :) If there are any notes or questions, please don't hesitate to let me know.

Thanks!

**Comment by n2o** [comment]
👍
